#!/usr/bin/env tsx
/**
 * Refresh the bundled Unraid GraphQL SDL fallback.
 *
 * Pinning policy
 * --------------
 * The bundled SDL must always come from a TAGGED release of `unraid/api` so
 * the namespace surface a user sees offline matches a known shipped Unraid
 * version. Floating heads (`main`) drift constantly and surface fields that
 * don't exist on most users' boxes — that's exactly the kind of mismatch
 * that produced the original "HTTP 400 with hidden GraphQL errors" bug
 * during local verification.
 *
 * The pinned tag is exposed at the top of this file so:
 *   1. It is reviewable in pull requests.
 *   2. The `local-fallback.graphql` header records the source for runtime
 *      diagnostics (`unraid.local.spec.version`).
 *   3. CI can fail if someone fetches an unpinned/`main` schema.
 *
 * Bumping the pin: change `PINNED_UNRAID_TAG`, run `npm run update-spec`,
 * then re-run `npm test` and the live-verification matrix.
 *
 * Override at runtime
 * -------------------
 *   UNRAID_SDL_URL=...   override the URL entirely (use for forks/dev)
 *   UNRAID_SDL_TAG=...   override just the tag (use to test a release
 *                        without changing the committed pin)
 *
 * The runtime loader prefers live introspection — the bundled SDL is a
 * startup-time safety net for deployments not yet pointed at a real Unraid
 * box. With introspection disabled (Unraid's default) the fallback is what
 * the LLM actually sees, so accuracy here matters.
 */

import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fetch as undiciFetch } from 'undici';

/**
 * Pinned upstream release tag. Bump deliberately, with verification.
 * Source: https://github.com/unraid/api/releases
 */
const PINNED_UNRAID_TAG = 'v4.35.0';

function defaultSdlUrl(tag: string): string {
  return `https://raw.githubusercontent.com/unraid/api/${tag}/api/generated-schema.graphql`;
}

async function main(): Promise<void> {
  const tag = process.env['UNRAID_SDL_TAG'] ?? PINNED_UNRAID_TAG;
  const url = process.env['UNRAID_SDL_URL'] ?? defaultSdlUrl(tag);
  const target = resolve(process.cwd(), 'src/spec/local-fallback.graphql');

  if (url.includes('/main/')) {
    console.error(
      '[update-spec] WARNING: fetching from `main` instead of a pinned tag. ' +
        'The bundled SDL may diverge from real Unraid releases.',
    );
  }

  console.error(`[update-spec] tag=${tag} url=${url}`);
  const res = await undiciFetch(url, {
    headers: { Accept: 'text/plain, */*;q=0.5' },
    signal: AbortSignal.timeout(30_000),
  });
  if (!res.ok) {
    throw new Error(`Failed to fetch SDL: HTTP ${String(res.status)} ${res.statusText}`);
  }
  const sdl = await res.text();
  if (!sdl.includes('type ') && !sdl.includes('schema ')) {
    throw new Error(
      `Fetched payload does not look like GraphQL SDL (length ${String(sdl.length)})`,
    );
  }
  // Stamp the header with the tag we pinned to so the runtime loader can
  // surface this in `unraid.local.spec.version` and so it's obvious in
  // diffs which release the schema came from.
  const header = [
    '# AUTO-GENERATED — do not hand-edit.',
    `# Source: ${url}`,
    `# Pinned tag: ${tag}`,
    `# Fetched: ${new Date().toISOString()}`,
    `# Generated by scripts/update-spec.ts (bump PINNED_UNRAID_TAG to refresh).`,
    '',
  ].join('\n');
  const stripped = sdl.replace(
    /^# AUTO-GENERATED[\s\S]*?(?=^[a-zA-Z"#]|^scalar |^type |^schema )/m,
    '',
  );
  const out = header + stripped.trimStart() + (stripped.endsWith('\n') ? '' : '\n');
  await writeFile(target, out, 'utf-8');
  console.error(`[update-spec] wrote ${target} (${String(out.length)} bytes, tag=${tag})`);
}

main().catch((err: unknown) => {
  console.error('[update-spec] FAILED:', err instanceof Error ? err.message : String(err));
  process.exit(1);
});
